name = "chor-sipahi"
compatibility_date = "2026-07-10"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "chor-sipahi-db"
database_id = "d1-placeholder-id-please-update"
migrations_dir = "./drizzle/migrations"

